export const FETCH_COLLECTION_FAILED = 'FETCH_COLLECTION_FAILED';
export const FETCH_COLLECTION_REQUEST = 'FETCH_COLLECTION_REQUEST';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
