export const FETCH_RECENT_GAMES_FAILED = 'FETCH_RECENT_GAMES_FAILED';
export const FETCH_RECENT_GAMES_REQUEST = 'FETCH_RECENT_GAMES_REQUEST';
export const FETCH_RECENT_GAMES_SUCCESS = 'FETCH_RECENT_GAMES_SUCCESS';
