export const FETCH_REVIEWS_OF_THE_WEEK_REQUEST =
  'FETCH_REVIEWS_OF_THE_WEEK_REQUEST';
export const FETCH_REVIEWS_OF_THE_WEEK_FAILED =
  'FETCH_REVIEWS_OF_THE_WEEK_FAILED';
export const FETCH_REVIEWS_OF_THE_WEEK_SUCCESS =
  'FETCH_REVIEWS_OF_THE_WEEK_SUCCESS';
