export const FETCH_COLLECTION_REVIEWS_FAILED =
  'FETCH_COLLECTION_REVIEWS_FAILED';
export const FETCH_COLLECTION_REVIEWS_REQUEST =
  'FETCH_COLLECTION_REVIEWS_REQUEST';
export const FETCH_COLLECTION_REVIEWS_SUCCESS =
  'FETCH_COLLECTION_REVIEWS_SUCCESS';
