export const FETCH_MY_PROFILE_FAILED = 'FETCH_MY_PROFILE_FAILED';
export const FETCH_MY_PROFILE_REQUEST = 'FETCH_MY_PROFILE_REQUEST';
export const FETCH_MY_PROFILE_SUCCESS = 'FETCH_MY_PROFILE_SUCCESS';

export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
