export const FETCH_POPULAR_GAMES_FAILED = 'FETCH_POPULAR_GAMES_FAILED';
export const FETCH_POPULAR_GAMES_REQUEST = 'FETCH_POPULAR_GAMES_REQUEST';
export const FETCH_POPULAR_GAMES_SUCCESS = 'FETCH_POPULAR_GAMES_SUCCESS';