export const SUBMIT_RATINGS_FAILED = 'SUBMIT_RATINGS_FAILED';
export const SUBMIT_RATINGS_REQUEST = 'SUBMIT_RATINGS_REQUEST';
export const SUBMIT_RATINGS_SUCCESS = 'SUBMIT_RATINGS_SUCCESS';

export const SUBMIT_REVIEW_FAILED = 'SUBMIT_REVIEW_FAILED';
export const SUBMIT_REVIEW_REQUEST = 'SUBMIT_REVIEW_REQUEST';
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS';
