export const LIKE_REVIEW_REQUEST = 'LIKE_REVIEW_REQUEST';
export const LIKE_REVIEW_FAILED = 'LIKE_REVIEW_FAILED';
export const LIKE_REVIEW_SUCCESS = 'LIKE_REVIEW_SUCCESS';

export const UNLIKE_REVIEW_REQUEST = 'UNLIKE_REVIEW_REQUEST';
export const UNLIKE_REVIEW_FAILED = 'UNLIKE_REVIEW_FAILED';
export const UNLIKE_REVIEW_SUCCESS = 'UNLIKE_REVIEW_SUCCESS';
