export const FETCH_LATEST_USERS_FAILED = 'FETCH_LATEST_USERS_FAILED';
export const FETCH_LATEST_USERS_REQUEST = 'FETCH_LATEST_USERS_REQUEST';
export const FETCH_LATEST_USERS_SUCCESS = 'FETCH_LATEST_USERS_SUCCESS';
