export const FETCH_USER_OF_THE_WEEK_FAILED = 'FETCH_USER_OF_THE_WEEK_FAILED';
export const FETCH_USER_OF_THE_WEEK_REQUEST = 'FETCH_USER_OF_THE_WEEK_REQUEST';
export const FETCH_USER_OF_THE_WEEK_SUCCESS = 'FETCH_USER_OF_THE_WEEK_SUCCESS';
