export const FETCH_ALL_REVIEWS_REQUEST = 'FETCH_ALL_REVIEWS_REQUEST';
export const FETCH_ALL_REVIEWS_FAILED = 'FETCH_ALL_REVIEWS_FAILED';
export const FETCH_ALL_REVIEWS_SUCCESS = 'FETCH_ALL_REVIEWS_SUCCESS';
