export const FETCH_USER_RATINGS_FAILED = 'FETCH_USER_RATINGS_FAILED';
export const FETCH_USER_RATINGS_REQUEST = 'FETCH_USER_RATINGS_REQUEST';
export const FETCH_USER_RATINGS_SUCCESS = 'FETCH_USER_RATINGS_SUCCESS';

export const FETCH_RATINGS_AVERAGE_FAILED = 'FETCH_RATINGS_AVERAGE_FAILED';
export const FETCH_RATINGS_AVERAGE_REQUEST = 'FETCH_RATINGS_AVERAGE_REQUEST';
export const FETCH_RATINGS_AVERAGE_SUCCESS = 'FETCH_RATINGS_AVERAGE_SUCCESS';
