// fetch game from IGDB api
export const FETCH_GAME_FAILED = 'FETCH_GAME_FAILED';
export const FETCH_GAME_REQUEST = 'FETCH_GAME_REQUEST';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';

// save the data get from IGDB api in our database
export const FETCH_POST_GAME_FAILED = 'FETCH_POST_GAME_FAILED';
export const FETCH_POST_GAME_REQUEST = 'FETCH_POST_GAME_REQUEST';
export const FETCH_POST_GAME_SUCCESS = 'FETCH_POST_GAME_SUCCESS';

// fetch game infos from our database
export const FETCH_GAME_IN_BASE_FAILED = 'FETCH_GAME_IN_BASE_FAILED';
export const FETCH_GAME_IN_BASE_REQUEST = 'FETCH_GAME_IN_BASE_REQUEST';
export const FETCH_GAME_IN_BASE_SUCCESS = 'FETCH_GAME_IN_BASE_SUCCESS';
